### ISSUE TITLE
Advice on setting up SSL, via caddy docker proxy

### ISSUE THREAD

**Issue by shrysr** [jamescherti/docker-oddmuse#1]
Hello James,
Thank you very much for creating this repo. Glad to see a fellow Emacs user in Canada!

I've been trying in vain to use your image to deploy oddmuse using a caddy reverse proxy (<https://github.com/lucaslorentz/caddy-docker-proxy>), and I have not been successful in enabling SSL.

My goal is to re-setup some personal oddmuse wikis using this image, and in addition start hosting a mirror as well as a rsync backup of the Emacswiki. 

I would love pointers and advice when you have the time.

There is a sample docker-compose.yml below. I have other other services deployed using this docker-compose setup and https works fine with those. 

I have also tried using your setup with modifications, with a local build - like adding `a2enmod ssl` and `EXPOSE 443` and experimented with virtual host configurations on 443. None worked - I'm including a screenshot for good measure.

    networks:
      caddy:
        external: true
      
    services:
      # Caddy with docker reverse proxy
      caddy:
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        ports:
          - 80:80
          - 443:443
        environment:
          - CADDY_INGRESS_NETWORKS=caddy
        networks:
          - caddy
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./caddy_data:/data
        restart: unless-stopped
    
      mywiki:
        image: jamescherti/oddmuse
        container_name: mywiki
        networks:
          - caddy
        labels:
          caddy: mywiki.ragavan.cc
          caddy.reverse_proxy: "{{upstreams 80}}"
        volumes:
          - /home/shrysr/apps/oddmusewikis/mywiki:/wiki
        environment:                
          - ODDMUSE_URL_PATH=/wiki
        restart: unless-stopped

<img width="489" alt="Screenshot 2024-07-16 at 5 32 17 PM" src="https://github.com/user-attachments/assets/dea018ef-8d1f-4d7d-9bf9-544692198054">

**Comment by shrysr** [comment]
Adding a note that for some reason, a test mirror of the emacswiki does not appear to have the same issue: https://emacswikimirror.ragavan.cc : notice that the links all point to emacswiki.org , and this needs to be fixed (among other things), but using the above domain link does not show the ssl issue. 
All I did was to rsync the emacswiki as described here https://www.emacswiki.org/emacs/Rsync_repository and `chown a+x` the folder from within the docker container.

**Comment by jamescherti** [comment]
Thank you for reaching out and for your kind words. I'm also delighted to see more Emacs enthusiasts working on interesting projects in Canada and also all around the world.

Regarding your issue with enabling SSL using the Caddy reverse proxy for the Oddmuse container, it appears that the issue has been resolved:
![image](https://github.com/user-attachments/assets/bfd7140b-7159-4856-8da0-b505e010b02b)

**Comment by jamescherti** [comment]
Thank you for reaching out and for your kind words. I'm also delighted to see more Emacs enthusiasts working on interesting projects in Canada and also all around the world.

Regarding your issue with enabling SSL using the Caddy reverse proxy for the Oddmuse container, it appears that the issue has been resolved:
![image](https://github.com/user-attachments/assets/af281478-1254-441a-8880-1ded69f1e669)

**Comment by shrysr** [comment]
Thanks for taking a look - Your screenshot is pointed to a different URL than the one in the docker-compose file in my comment. I was referring to https://mywiki.ragavan.cc/wiki - and I still do not have  full SSL.

**Comment by jamescherti** [comment]
You're welcome, @shrysr.

FYI: The SSL appears to be functioning correctly for the URL you provided:
![image](https://github.com/user-attachments/assets/2ae57d1d-cf5c-4dba-b70b-fb5ba4a81de8)
